config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :posts

  resources :calendars
  resources :events

  get 'about' => 'home#about'
  root :to =>'home#index'

  resources :users do
    resources :calendars
    resources :events
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
  #  has_many :calendars, dependent: :destroy
   belongs_to :user

  # before_create :update_created_by
  # before_update :update_modified_by
  #
  #
  # def update_created_by
  #   self.created_by = current_user_id
  # end
  #
  # def update_modified_by
  #   self.modified_by = current_user_id
  # end
  #
  # def current_user_id
  #   User.current_user.try(:id)
  # end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  # before_action :require_sign_in, except: [:index, :show]
  # before_action :authorize_user, except: [:index, :show]
  def index
    @user = User.find(params[:user_id])
    @events = @user.events

  end

  def new
    @user = User.find(current_user)
    @event = @user.events.new
    if current_user.admin?
      @select_options = [['Scheduled day off','Scheduled day off'],['Requested for PTO', 'Requested for PTO'],['PTO has NOT been approved', 'PTO has NOT been approved'],['PTO approved', 'PTO approved']]
    else #current_user.member?
      @select_options = [['Scheduled day off','Scheduled day off'],['Requested for PTO', 'Requested for PTO']]
    end
  end

  def create
      @user = User.find(params[:user_id])
      @event = @user.events.build(event_params)
      if @event.save
        redirect_to user_calendars_path(@user)
      else
        render :new
      end
  end



  def update
     @event = Event.find(params[:id])
     authorize @event
     if @event.update (event_params)
       redirect_to user_event_path
     else
        render :edit
     end
   end

  def show
    @event = Event.all
  end

  def edit
    @event = Event.find(params[:id])
  end

  def destroy
    user = User.find(params[:user_id])
    @event = Event.find(params[:id])
     if @event.destroy
       flash[:notice] = "\"#{@event}\" was deleted successfully."
       redirect_to user_events_path(user.id)
     else
       flash.now[:alert] = "There was an error deleting the event."
       render :show
     end
  end


  private
  def event_params
    params.require(:event).permit(:name, :occurs_on, :description, :public)
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def user_is_authorized_for_events?
       current_user && current_user.admin?
  end

  def display_event_content?(event)
      (event.private && (event.user == current_user || current_user.admin?)) || !event.private
    end
    # def user_authorized_for_private?(event)
    #   ((event.user == current_user || !event.user) && current_user.premium?) || current_user.admin?
    # end
    def display_in_index?(event)
      event.user != current_user && display_event_content?(event)
    end
end

app/views/events/edit.html.erb
<h1>Edit Event</h1>

 <div class="row">
   <div class="col-md-4">

   </div>
   <div class="col-md-8">
     <%= form_for @event do |f| %>
       <div class="form-group">
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control', placeholder: "Enter event title" %>
       </div>
       <div class="form-group">
         <%= f.label :body %>
         <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter event body" %>
       </div>
       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>

app/views/events/index.html.erb
<div class="col-md-4">
  <%= link_to "New Event", new_event_path, class: 'btn btn-default btn-sm' %>
  <%= link_to "Calendar", user_calendars_path, class: 'btn btn-default btn-sm' %>
</div>
<h1>All Events</h1>
<style>

  table, th, td {
      border: 1px solid black;
      padding: 5px;
  }
  table {
      border-spacing: 15px;
  }

</style>
<body>
<table style="width:100%">
      <th colspan="5"></th>
        <tr>
          <th>#ID</th>
          <th>Date</th>
          <th>Event Name</th>
          <th>Action</th>
        </tr>
      <tbody>
          <% @events.each do |event| %>
          <tr>
              <td><%=  event.id %></td>
              <td><%=  event.occurs_on %></td>
              <td><%=  event.name %></td>
              <td><%= link_to "Delete event", user_event_path(@user, event), method: :delete, class: 'btn btn-default', data: { confirm: 'Are you sure you want to delete this event?' } %></td>
          </tr>
          <% end %>
      </tbody>
    </table>
  </body>

app/views/events/new.html.erb
<h3> New Event for PTO </h3>
  <%= form_for [@user, @event] do |f| %>
    <%= f.select :name, @select_options %>

    <%= f.hidden_field :occurs_on, value: params[:date] %><br />
      <%= f.submit %>
    <%- end %><br>

app/views/events/show.html.erb
<h1><%= @event.name %></h1>
<div>
    <% if user_is_authorized_for_event? %>
      <%= link_to "Edit event", edit_event_path, class: 'btn btn-success' %>
    <% end %>

    <% if current_user %>
      <div class="col-md-4">
        <%= link_to "New Event", new_event_path(@event), class: 'btn btn-success' %>
      </div>
     <% end %>
 </div>