config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :posts

  resources :calendars
  resources :events

  get 'about' => 'home#about'
  root :to =>'home#index'

  resources :users do
    resources :calendars
    resources :events
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Listing Posts</h3>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= post.user.name %></td>
        <td><%= post.user.email %></td>
        <td><%= link_to 'Show', post %></td><br>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>
<% if current_user && current_user.admin? %>
    <div class="col-md-4">
      <%= link_to "New event", new_event_path, class: 'btn btn-success' %>
    </div>
  <% end %>

app/views/posts/show.html.erb
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Title:</strong>
    <%= @post.title %>
  </p>
  <br >
  <p>
    <strong>Content:</strong>
    <%= @post.content %> <br>
  </p>
  <br>
  <% if user_is_authorized_for_post?(@post) %>
       <div class="col-md-4">
         <%= link_to "Edit Post", edit_event_post_path(@post.event, @post), class: 'btn btn-success' %>
         <%= link_to "Delete Post", [@post.event, @post], method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this post?' } %>
       </div>
     <% end %>